Update sealed secrets controller to 0.9.6 from 0.9.0 (#29)
If you try to run `poetry run invoke-kubernetes` on a too new Kubernetes cluster, you will get the following error message:

error: unable to recognize "kube/01-sealed-secrets-controller.yaml": no matches for kind "Deployment" in version "apps/v1beta2"

According to https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ the v1.16 release of kubernetes stopped serving the deprecated API apps/v1beta for Deployment.

According to the release notes for sealed secrets, the issue was resolved in version 0.9.1:https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#v091

Considered it best to update all the way to the latest version, thus updating to 0.9.6.

The updated version was fetched from http://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.6/controller.yaml

Azure does not yet offer kubernetes 1.16, but the latest version of minikube is already running kubernetes 1.17.